# Phase 3: Data Preprocessing

In this phase, I will prepare the MNIST images before training a machine learning model.

The main preprocessing steps are:

- Load the MNIST dataset
- Normalize pixel values from 0–255 to 0–1
- Reshape the image data if needed
- Prepare the labels for model training
- Confirm that the preprocessing worked correctly

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

In [13]:
(x_train, y_train) , (x_test, y_test) = mnist.load_data()

In [14]:
print("Before preprocessing:")
print("Minimum pixel value:", x_train.min())
print("Maximum pixel value:", x_train.max())

Before preprocessing:
Minimum pixel value: 0
Maximum pixel value: 255


In [15]:
x_train_norm = x_train / 255.0
x_test_norm = x_test / 255.0

In [16]:
print("After normalization:")
print("Minimum pixel value:", x_train_norm.min())
print("Maximum pixel value:", x_train_norm.max())

After normalization:
Minimum pixel value: 0.0
Maximum pixel value: 1.0


## Normalization

The original MNIST pixel values range from 0 to 255.

To prepare the images for neural network training, I normalized the pixel values by dividing them by 255.0.

After normalization:

- 0 remains 0.0
- 255 becomes 1.0
- values between 0 and 255 become decimal values between 0 and 1

This helps the model train more efficiently because the input values are smaller and more stable.

In [17]:
x_train_cnn = x_train_norm.reshape(-1,28,28,1)
x_test_cnn = x_test_norm.reshape(-1,28,28,1)

In [18]:
print("Original training shape:", x_train_norm.shape)
print("CNN training shape:", x_train_cnn.shape)

print("Original test shape:", x_test_norm.shape)
print("CNN test shape:", x_test_cnn.shape)

Original training shape: (60000, 28, 28)
CNN training shape: (60000, 28, 28, 1)
Original test shape: (10000, 28, 28)
CNN test shape: (10000, 28, 28, 1)


## Reshaping for CNN Input

The original MNIST images have the shape `(28, 28)`, which means each image is a 2D grayscale image.

For a Convolutional Neural Network, TensorFlow expects image data to include a channel dimension.

Before reshaping:

- Training data shape: `(60000, 28, 28)`
- Test data shape: `(10000, 28, 28)`

After reshaping:

- Training data shape: `(60000, 28, 28, 1)`
- Test data shape: `(10000, 28, 28, 1)`

The final `1` represents the grayscale color channel.

In [20]:
print("first 10 training labels:", y_train[:10])
print("label shape:", y_train.shape)

first 10 training labels: [5 0 4 1 9 2 1 3 1 4]
label shape: (60000,)


## Label Preparation

The MNIST labels are already stored as integers from 0 to 9.

For this project, I will initially keep the labels in integer format because TensorFlow/Keras can train a classification model using integer labels with `sparse_categorical_crossentropy`.

This means:

- The image of digit 0 has label `0`
- The image of digit 1 has label `1`
- The image of digit 9 has label `9`

No one-hot encoding is needed at this stage.

In [21]:
print("final training data shape:", x_train_cnn.shape)
print("final test data shape:", x_test_cnn.shape)
print("training label shape:" ,y_train.shape)
print("test label shape:" ,y_test.shape)
print("training data type:", x_train_cnn.dtype)
print("Minimum pixel value:", x_train_cnn.min())
print("Maximum pixel value:", x_train_cnn.max())

final training data shape: (60000, 28, 28, 1)
final test data shape: (10000, 28, 28, 1)
training label shape: (60000,)
test label shape: (10000,)
training data type: float64
Minimum pixel value: 0.0
Maximum pixel value: 1.0


## Phase 3 Summary: Data Preprocessing

In this phase, I prepared the MNIST dataset for future model training.

### Completed Tasks

- Loaded the MNIST dataset
- Checked the original pixel value range
- Normalized pixel values from 0–255 to 0–1
- Checked that normalization worked correctly
- Reshaped the images for CNN input
- Checked the final image shapes
- Confirmed that labels are stored as integers from 0 to 9
- Confirmed the final preprocessed data shapes and pixel range

### Final Data Format

After preprocessing:

- Training images shape: `(60000, 28, 28, 1)`
- Test images shape: `(10000, 28, 28, 1)`
- Training labels shape: `(60000,)`
- Test labels shape: `(10000,)`
- Pixel values range from `0.0` to `1.0`

### Key Observation

The MNIST images are now normalized and reshaped correctly for a Convolutional Neural Network.  
The labels do not need one-hot encoding at this stage because I can use `sparse_categorical_crossentropy` later during model training.